### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [is541-sibsutis/unit-converter#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:

1. В [wiki](https://github.com/is541-sibsutis/unit-converter/wiki) проекта написана статья с ТЗ.
1. В [issues](https://github.com/is541-sibsutis/unit-converter/issues) созданы задачи.
1. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by MypMypMyp** [comment]
Предварительное ТЗ.
Что можно добавить?

**Comment by evgeny-p** [comment]
1. Нужно более строго описать формат входных данных. По текущему словесному описанию формат неясен.
  > Вводим величину, из чего хотим перевести, во что хотим перевести и число.
  По этому описанию можно предложить множество вариантов ввода:
  *  `<n> <from-unit> to <to-unit>`, пример: `1 km to meters`
  *  `<from-unit> <to-unit> <n>`, пример: `km meter 10`
  *  Или же это будет интеравтивная сессия вида:

    ```
    You got: <n> <from-unit>
    You want: <to-unit>
    ```

1. Консольные приложения, работающие в интерактивном режиме, часто поддерживают историю команд. С помощью стрелок можно перемещаться по истории. Предлагаю предусмотреть такой функционал.

1. Как будет производиться выход из приложения? Специальная команда? По сигналу?

1. Идеологически правильно было бы предусмотреть и неинтерактивный режим работы приложения:

  > Doug McIlroy, the inventor of Unix pipes and one of the founders of the Unix tradition, had this to say at the time:

   > 1. (…)
   > 1. Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. **Don't insist on interactive input.**

   [Eric Steven Raymond, The Art of Unix Programming: Basics of the Unix Philosophy](http://www.catb.org/esr/writings/taoup/html/ch01s06.html)

  В этом случае нужно описать опции командной строки. См. man-страницу любой стандартной юниксовой утилиты.

1. > Информация о поддерживаемых величинах и коэффициентах для перевода хранится в текстовом файле.

  Нужна спецификация формата файла.

1. По какому принципу выбраны величины, поддерживаемые приложением? Алгоритм перевода общий, не должно быть привязки к конкреному набору величин. Следует продумать разделение логики приложения и данных. Задокументировать в ТЗ.

1. > Так же есть команда Help в которой будет описание возможным команд.
  «Возможные команды» упомянуты только здесь.

1. Некоторые требования к заголовкам:
  1. Посмотрите, как в markdown оформляются заголовки.
  1. Заголовки должны быть краткими.
  1. Без лишней пунктуации.

  Текущие заголовки могут быть сокращены до:
  > ## Функционал проекта

  > ## Пользовательский интерфейс

  К ним могут быть добавлены (только пример):
  > ## Формат базы данных величин

  > ## Алгоритм перевода

1. Документ нужно вычитать на предмет ошибок и опечаток.

1. ТЗ станет частью отчета по курсовой работе. Следовательно, нужно придерживаться соответствующего стиля изложения. Например:
  > Приложение будет консольным. Работает в интерактивном режиме.

  Незначительные изменения могут придать строгость формулировкам:
  > Разрабатывается консольное приложение. В качестве основного режима работы предлагается реализовать интерактивный.

  Эта фраза скорее рекламная, никакой полезной нагрузки для технического задания не несет:
  > Применяется в разных сферах, для конвертирования различных величин.

По текущим наработкам больше мыслей не возникает. Возможно, появятся новые вопросы по мере доработки ТЗ.

**Comment by MypMypMyp** [comment]
Возможное исправлено.
Может быть какие-нибудь ещё вопросы?

**Comment by evgeny-p** [comment]
1. > Входными данными служат положительные и отрицательные вещественные числа. 

  Формулировка противоречит примеру.

1. > exit, clear, add, delete

  В ТЗ описана только команда exit.

1.  Все величины будут храниться в одном файле? В памяти предлагается хранить единственный граф для всех величин? Как алгоритмически предлагается определять ситуацию, в которой невозможно выполнить перевод из величины A в величину B?

1. В конце заголовков точки не ставятся.

Приступайте к созданию задач.

**Comment by MypMypMyp** [comment]
сделано

**Comment by MypMypMyp** [comment]
так что на счет таких задач?

**Comment by evgeny-p** [comment]
С такого списка задач можно стартовать. В процессе по необходимости допускается заводить новые задачи.
